name: Twitter Bot
on:
  schedule:
    - cron: "0 */4 * * *" # Every 4 hours UTC
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.1"
          cache: "npm"
      - run: npm install
      - env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          cat << EOF > SECRETS.js
          module.exports = {
            APP_KEY: "$APP_KEY",
            APP_SECRET: "$APP_SECRET",
            ACCESS_TOKEN: "$ACCESS_TOKEN",
            ACCESS_SECRET: "$ACCESS_SECRET",
            GEMINI_API_KEY: "$GEMINI_API_KEY"
          };
          EOF
      - run: node index.js